{"name": "test_auth_biometric", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'Failed', but got 'SUCCEEDED'\nassert 'SUCCEEDED' == 'Failed'\n  \n  \u001b[0m\u001b[91m- Failed\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  \u001b[92m+ SUCCEEDED\u001b[39;49;00m\u001b[90m\u001b[39;49;00m", "trace": "self = <TestCases.test_biometric_auth.Test_Bio_Auth object at 0x000002A7CB29CB90>\n\n    def test_auth_biometric(self):\n        home = HomeScreen(self.driver)\n        home.goToAndroidBioMetric().clickOnPassCallBack()\n        actualMessage = home.goToAndroidBioMetric().getStatusMessage()\n    \n        expectedMessage = 'Failed'\n    \n>       assert actualMessage == expectedMessage, f\"Expected '{expectedMessage}', but got '{actualMessage}'\"\nE       AssertionError: Expected 'Failed', but got 'SUCCEEDED'\nE       assert 'SUCCEEDED' == 'Failed'\nE         \nE         \u001b[0m\u001b[91m- Failed\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\nE         \u001b[92m+ SUCCEEDED\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n\ntest_biometric_auth.py:14: AssertionError"}, "attachments": [{"name": "log", "source": "96e20fdd-81b8-44b9-ac7d-6a8bd6853977-attachment.txt", "type": "text/plain"}], "start": 1754398294342, "stop": 1754398296730, "uuid": "b23f49c5-c66d-4985-be8e-c6b8e8269de8", "historyId": "476a68ff226e5853fa3aa36fa902fed3", "testCaseId": "476a68ff226e5853fa3aa36fa902fed3", "fullName": "test_biometric_auth.Test_Bio_Auth#test_auth_biometric", "labels": [{"name": "suite", "value": "test_biometric_auth"}, {"name": "subSuite", "value": "Test_Bio_Auth"}, {"name": "host", "value": "Abhishek"}, {"name": "thread", "value": "8020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_biometric_auth"}], "titlePath": ["test_biometric_auth.py", "Test_Bio_Auth"]}