{"uuid": "ba6b0359-4ad5-4a71-ab4e-c9cb7b1d237d", "children": ["595e3e1e-f6a3-4a4d-a11c-7b4fee7f41f9"], "befores": [{"name": "appium_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms\n    at getResponseForW3CError (C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1143:9)\n    at asyncHandler (C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:487:57)\n", "trace": "  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\TestCases\\conftest.py\", line 31, in appium_driver\n    driver = webdriver.Remote(url, options= AppiumOptions().load_capabilities(cap))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 253, in __init__\n    super().__init__(\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 261, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 344, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\dell\\PycharmProjects\\Appium_Python\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754398427401, "stop": 1754398449783}], "start": 1754398427401, "stop": 1754398449966}